2023-07-10 09:53:54.549 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "16"

2023-07-10 10:39:50.950 [info] ERROR:pygls.protocol:Failed to handle request 161 textDocument/hover HoverParams(text_document=TextDocumentIdentifier(uri='file:///workspace/Afrik-kitchen/view_menu/urls.py'), position=6:0, work_done_token=None)
Traceback (most recent call last):
  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 337, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 261, in _execute_request
    self._send_response(msg_id, handler(params))
  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 378, in hover
    jedi_script.help(
  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper
    raise ValueError('`column` parameter (%d) is not in a valid range '
ValueError: `column` parameter (1) is not in a valid range (0-0) for line 7 ('\n').

2023-07-10 10:39:50.952 [info] [Error - 10:39:50 AM] Request textDocument/hover failed.
2023-07-10 10:39:50.952 [info]   Message: ValueError: `column` parameter (1) is not in a valid range (0-0) for line 7 ('\n').
  Code: -32602 
{'traceback': ['  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 337, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 261, in _execute_request\n    self._send_response(msg_id, handler(params))\n', '  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 378, in hover\n    jedi_script.help(\n', '  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper\n    raise ValueError(\'`column` parameter (%d) is not in a valid range \'\n']}
2023-07-10 10:45:01.160 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "169"

2023-07-10 10:45:52.043 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "187"

2023-07-10 10:46:20.751 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "205"

2023-07-10 10:47:49.230 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "253"

2023-07-10 10:48:16.120 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "279"

2023-07-10 10:53:46.267 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "342"

2023-07-10 11:01:54.138 [info] ERROR:pygls.protocol:Failed to handle request 369 textDocument/hover HoverParams(text_document=TextDocumentIdentifier(uri='file:///workspace/Afrik-kitchen/view_menu/urls.py'), position=7:0, work_done_token=None)
Traceback (most recent call last):
  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 337, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 261, in _execute_request
    self._send_response(msg_id, handler(params))
  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 378, in hover
    jedi_script.help(
  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper
    raise ValueError('`column` parameter (%d) is not in a valid range '
ValueError: `column` parameter (1) is not in a valid range (0-0) for line 8 ('\n').

2023-07-10 11:01:54.139 [info] [Error - 11:01:54 AM] Request textDocument/hover failed.
2023-07-10 11:01:54.139 [info]   Message: ValueError: `column` parameter (1) is not in a valid range (0-0) for line 8 ('\n').
  Code: -32602 
{'traceback': ['  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 337, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 261, in _execute_request\n    self._send_response(msg_id, handler(params))\n', '  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 378, in hover\n    jedi_script.help(\n', '  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper\n    raise ValueError(\'`column` parameter (%d) is not in a valid range \'\n']}
2023-07-10 11:17:08.436 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "457"

2023-07-10 11:21:17.394 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "465"

2023-07-10 11:21:17.547 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "466"

2023-07-10 11:21:32.127 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "474"

2023-07-10 11:26:09.671 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "512"

2023-07-10 11:28:23.408 [info] ERROR:pygls.protocol:Failed to handle request 576 textDocument/hover HoverParams(text_document=TextDocumentIdentifier(uri='file:///workspace/Afrik-kitchen/view_menu/urls.py'), position=8:0, work_done_token=None)
Traceback (most recent call last):
  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 337, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 261, in _execute_request
    self._send_response(msg_id, handler(params))
  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 378, in hover
    jedi_script.help(
  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper
    raise ValueError('`column` parameter (%d) is not in a valid range '
ValueError: `column` parameter (1) is not in a valid range (0-0) for line 9 ('\n').

2023-07-10 11:28:23.409 [info] [Error - 11:28:23 AM] Request textDocument/hover failed.
2023-07-10 11:28:23.409 [info]   Message: ValueError: `column` parameter (1) is not in a valid range (0-0) for line 9 ('\n').
  Code: -32602 
{'traceback': ['  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 337, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 261, in _execute_request\n    self._send_response(msg_id, handler(params))\n', '  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 378, in hover\n    jedi_script.help(\n', '  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper\n    raise ValueError(\'`column` parameter (%d) is not in a valid range \'\n']}
2023-07-10 11:31:51.706 [info] ERROR:pygls.protocol:Failed to handle request 618 textDocument/hover HoverParams(text_document=TextDocumentIdentifier(uri='file:///workspace/Afrik-kitchen/view_menu/urls.py'), position=8:0, work_done_token=None)
Traceback (most recent call last):
  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 337, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 261, in _execute_request
    self._send_response(msg_id, handler(params))
  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 378, in hover
    jedi_script.help(
  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper
    raise ValueError('`column` parameter (%d) is not in a valid range '
ValueError: `column` parameter (1) is not in a valid range (0-0) for line 9 ('\n').

2023-07-10 11:31:51.707 [info] [Error - 11:31:51 AM] Request textDocument/hover failed.
2023-07-10 11:31:51.707 [info]   Message: ValueError: `column` parameter (1) is not in a valid range (0-0) for line 9 ('\n').
  Code: -32602 
{'traceback': ['  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 337, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 261, in _execute_request\n    self._send_response(msg_id, handler(params))\n', '  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 378, in hover\n    jedi_script.help(\n', '  File "/workspace/.vscode-remote/extensions/ms-python.python-2023.12.0-universal/pythonFiles/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper\n    raise ValueError(\'`column` parameter (%d) is not in a valid range \'\n']}
2023-07-10 12:06:31.669 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "645"

2023-07-10 12:07:33.108 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "741"

2023-07-10 12:07:33.505 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "743"

2023-07-10 12:07:33.514 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "742"

2023-07-10 12:13:41.546 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "799"

2023-07-10 12:13:48.006 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "809"

2023-07-10 12:13:55.231 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "821"

2023-07-10 12:14:05.269 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "843"

2023-07-10 12:14:19.120 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "862"

2023-07-10 12:14:19.124 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "861"

2023-07-10 12:14:19.166 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "864"

2023-07-10 12:14:19.170 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "863"

2023-07-10 12:14:27.247 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "880"

2023-07-10 12:14:27.248 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "879"

2023-07-10 12:14:27.254 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "881"

2023-07-10 12:14:40.352 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "897"

2023-07-10 12:14:57.865 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "900"

2023-07-10 12:15:16.606 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "910"

2023-07-10 12:15:29.649 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "922"

2023-07-10 12:16:25.307 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "956"

2023-07-10 12:32:32.898 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "999"

2023-07-10 12:32:55.947 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "1021"

